### ISSUE TITLE
Write testcases related to a class not existing

### ISSUE THREAD

**Issue by RezwanArefin01** [AY2223S1-CS2103T-T12-1/tp#110]
Need testcases for the following places where a class does not exist in the app:
- Add command
- Edit command
- Storage load

**Comment by Berted** [comment]
Needs more clarification.

**Comment by RezwanArefin01** [comment]
@Berted For example in storage load: if the student object specified a module that does not exist in the module array. The add command is still missing this test. 

The edit command don't need it anymore, since class is not editable with edit now.
