### ISSUE TITLE
As a user, I can see a list of all sessions for a class

### ISSUE THREAD

**Issue by Berted** [AY2223S1-CS2103T-T12-1/tp#115]
Perhaps can be sub-divided into two subtasks:
- [x] Getting the basics working and implementing a rudimentary CLI version
- [x] Using GUI to improve on the design

**Comment by Berted** [comment]
The basics will be working after PR #114 is merged. @optionalemon are you willing to take the UI creation part?

**Comment by optionalemon** [comment]
> The basics will be working after PR #114 is merged. @optionalemon are you willing to take the UI creation part?

Yep that's alright!

**Comment by Bubbl3T** [comment]
I think we should create a new issue regarding using GUI to display the list of classes and sessions. Closing this issue for now since changes are irrelevant in milestone v1.2b
