### ISSUE TITLE
Bug: deleting a session does not unassign students from the session

### ISSUE THREAD

**Issue by RezwanArefin01** [AY2223S1-CS2103T-T12-1/tp#149]
As a result the data file is corrupted in the next run.

**Comment by Berted** [comment]
This seems to be a pretty redundant issue in multiple areas of the code, hence I propose the following solution:

Let us create methods within TaAssist to handle such behavior, i.e. deleteModuleClass, deleteSession etc. As TaAssist has complete access to both StudentList and ModuleList. This should also heavily improve abstraction over the current implementation we have right now.

**Comment by Berted** [comment]
@RezwanArefin01 Are you working on this? If not, I'd like to work on this.
