### ISSUE TITLE
Consider adding methods to `TestUtil` to help with testing

### ISSUE THREAD

**Issue by njxue** [AY2223S1-CS2103T-T12-1/tp#153]
Currently, commands like `AddcCommand` and `DeletecCommand` can only take in a Collection of `ModuleClasses` as arguments for their constructors. 
This makes it tedious to write test cases when we only want to test with 1 `ModuleClass`  (it does not affect the main code).

**Comment by Berted** [comment]
Personally, I don't think it's a good idea to write code just for testing. 

Perhaps we can consider adding additional code to TestUtils to handle such issues?

**Comment by njxue** [comment]
> 

Yea that sounds like a better idea. Changed title

**Comment by njxue** [comment]
> Personally, I don't think it's a good idea to write code just for testing.
> 
> Perhaps we can consider adding additional code to TestUtils to handle such issues?

Yea that sounds like a better idea. Changed title

**Comment by Berted** [comment]
The scope of this issue is too wide. In addition, there are now classes like `TypicalModuleClasses` and `ModuleClassBuilder` that help in this regard. This issue will be closed as completed.
