### ISSUE TITLE
Add tests for `SessionData` and `StudentModuleData` and their JSON-adapted versions

### ISSUE THREAD

**Issue by RezwanArefin01** [AY2223S1-CS2103T-T12-1/tp#188]

**Comment by Berted** [comment]
Is this still necessary with methods like `updateGrade`?

**Comment by RezwanArefin01** [comment]
@Berted `StudentModuleData` tests were added as part of #327. `SessionData` doesn't currently have any logic heavy component that requires testing.

However, we still need to test the Json adapted variants.
