### ISSUE TITLE
Bug: uncaught RuntimeException in `deletes` even when a session exists

### ISSUE THREAD

**Issue by njxue** [AY2223S1-CS2103T-T12-1/tp#214]
![image](https://user-images.githubusercontent.com/66546854/197983257-f99a5790-8a86-4ca5-ae2d-50cb5335fff3.png)

**Comment by RezwanArefin01** [comment]
I cannot remember the reason why `UniqieList#remove` requires `equals` equality. If it is not needed, then we may fix this issue by updating the `UniqueList#setElement` to compare by `isSame`.

**Comment by njxue** [comment]
> I cannot remember the reason why UniqieList#remove requires equals equality. If it is not needed, then we may fix this issue by updating the UniqueList#setElement to compare by isSame.

The bug turned out harder than expected to fix because the issue was on `ModuleClass` becoming immutable, so `removeSessions` calling `removeSession` multiple times on the same `ModuleClass` object does not work.
