### ISSUE TITLE
Bug regading `CommandResult`: possibly `focus` and `unfocus` in the same time.

### ISSUE THREAD

**Issue by Berted** [AY2223S1-CS2103T-T12-1/tp#232]
> I think the code looks fine for now. However, the current logic of sending instructions to UI using parameters in `CommandResult` can be improved with polymorphism. This also prevents bugs resulting from setting both `boolean focus` and `boolean unfocus` to `true`. This can be addressed in another issue.

_Originally posted by @Bubbl3T in https://github.com/AY2223S1-CS2103T-T12-1/tp/pull/226#pullrequestreview-1156892612_

**Comment by Berted** [comment]
Perhaps we can consider re-utilizing the previously implemented `focusLabelProperty`? JavaFX's properties should implement an `Observable` pattern of sorts, I'm sure we can use this to our advantage in UI to avoid adding additional fields to `CommandResult`. Albeit this implementation is servicable for now.

**Comment by Bubbl3T** [comment]
We can perhaps create a separate enum class `UiHandler` which can possibly contain something that the UI has to handle. In that case, the UI can also use a switch case to check which case to handle.

**Comment by Bubbl3T** [comment]
This can perhaps be solved by polymorphing the `CommandResult` class. More information will be provided in PR.
