### ISSUE TITLE
Feature flaw: Allow `session` command to create multiple sessions.

### ISSUE THREAD

**Issue by Bubbl3T** [AY2223S1-CS2103T-T12-1/tp#244]
Since sessions come with dates, is there a way we can design the command input so that the dates for the sessions are added correctly with the relevant dates?

**Comment by njxue** [comment]
How about only allowing multiple sessions of the same date (similar to the grade command)? 
I think it's fine to impose certain restrictions on the user.

Alternatively, we could pair the session names and dates together (eg. `s/session1 d/dateForSession1 s/session2 d/dateForSession2`) but this can be quite hard to implement without bugs.

**Comment by Bubbl3T** [comment]
Yes, I was thinking along the same lines as you, but if we require the user to pair session names with the dates, then we are forcing the user to key in dates for all the sessions, which will roughly be as good as making him create it one by one.

The other method of allowing multiple sessions of the same date sounds feasible. If we are planning to implement that, we will have to update the UG on the command usage.

**Comment by Bubbl3T** [comment]
Issue resolved.
