### ISSUE TITLE
[PE-D][Tester D] Duplicate checking for students does not take into account case of text

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T12-1/tp#278]
![image.png](https://raw.githubusercontent.com/XenonShawn/ped/main/files/7ba418c7-e7d2-4d24-952d-efba8f841505.png)

It would probably be expected that Roy and roy are the same person in this case, so it's not detecting this

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: XenonShawn/ped#2

**Comment by Bubbl3T** [comment]
This is unavoidable since it is possible for students to have duplicate names.
