### ISSUE TITLE
[PE-D][Tester D] No warnings raised when unassigning students when not from the class

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T12-1/tp#285]
Students can be unassigned from a class which they aren't in without an error or warning. Users might accidentally key in the index wrongly, so this might be an issue

![image.png](https://raw.githubusercontent.com/XenonShawn/ped/main/files/c500d410-e22c-4ad2-aa83-45f209336e9d.png)

![image.png](https://raw.githubusercontent.com/XenonShawn/ped/main/files/5efb1c37-b679-48a3-b7ae-148dfc9dd006.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: XenonShawn/ped#6

**Comment by Berted** [comment]
This was intended behaviour. However, I can see why users might not consider it as such. As such, I propose two fixes to help alleviate this issue:
- ~~Add a note to `CommandResult` stating certain indices were not changed as they were not assigned in the first place.~~
- Add a note in UG regarding this.

**Comment by Berted** [comment]
The first point can't be done due to v1.4's limitations.
