### ISSUE TITLE
[PE-D][Tester A] Wrong error message for adding classes

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T12-1/tp#286]
![Screenshot 2022-10-28 at 4.37.05 PM.png](https://raw.githubusercontent.com/Dilysss/ped/main/files/55aeb56f-9036-412f-9f91-f12293f2e83f.png)

When trying to add classes and one of the prefixes is wrong but the rest are correct, the error message states that 'Class names should be alphanumeric.' However, the error is not that the class names are not alphanumeric but that the prefix is wrong

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Dilysss/ped#7

**Comment by Berted** [comment]
Consider showing what part of the command went wrong, i.e. `Class name [CS1231 n/CS1231] is not alphanumeric`, so that the user can detect the mistake. This is the best solution we can implement in the v1.4's limited time.
