### ISSUE TITLE
[PE-D][Tester D] Repetition of Documentation

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T12-1/tp#300]
There are a few instances of documentation repetition throughout the UG, one of the more obvious examples is as follows. It may be good to either provide more information (or in the case of the clear command, a warning).

![image.png](https://raw.githubusercontent.com/XenonShawn/ped/main/files/44508630-78f0-4724-ba05-43dce8e0497c.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: XenonShawn/ped#13

**Comment by Bubbl3T** [comment]
Delete the explanation for the format.
