### ISSUE TITLE
[PE-D][Tester D] Incorrect JavaFX version

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T12-1/tp#310]
JavaFX keeps throwing warnings in the console

![image.png](https://raw.githubusercontent.com/XenonShawn/ped/main/files/ff823c57-90de-4ca8-a240-6dacbc1f1090.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: XenonShawn/ped#16

**Comment by Bubbl3T** [comment]
Check JavaFX FXML file versions.
