### ISSUE TITLE
[PE-D][Tester E] Invalid address inputs for `add`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T12-1/tp#316]
**Description**

Currently, there is no restriction on the address inputs (all strings are valid). This means that an address like `a/Commonwealth c/loseblock123` should technically be allowed by TA Assist (since addresses like `a/Commonwealth b/loseblock123` are allowed), and there is no restriction on the address specified in the UG or command parser.

However, quite clearly, there would be issues parsing an address`a/Commonwealth c/loseblock123` because the command is ambiguous, and parser would pick `c/loseblock123` as a class parameter rather than being part of the address.

Since most addresses generally do not have a "/" in them, perhaps it would be better to impose character constraints on addresses, just like how other parameters do not allow slashes in them?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: chloeelim/ped#8

**Comment by Berted** [comment]
Address will validate against any `/`. More UG info will be added in this regard.

**Comment by Berted** [comment]
Actually, this seems like a pretty niche problem, having `<white_space>x/` for some character `x` for address seems highly unlikely, validating in this scenario would only highly likely cause proper addresses to be invalidated, i.e. in Indonesia, `Jalan Sumatra No. 10/20C` is a perfectly valid address.

We'll add some notes regarding this issue on the appending on parameters and its constraints. Nice spot however!

**Comment by Berted** [comment]
Added note on documentation due to its relatively "niche" issue.
