### ISSUE TITLE
Add use cases to DG

### ISSUE THREAD

**Issue by njxue** [AY2223S1-CS2103T-T12-1/tp#32]

**Comment by Berted** [comment]
Common  Problems in Use Cases. Examples:
- Important use cases missing (a use case is important if it involves a user interaction that is worthy of documenting e.g., it has multiple extensions -- this is not the same as the feature being important)
- Formatting/notational errors
- Incorrect step numbering
- Unnecessary UI details mentioned
- Missing/unnecessary steps
- Missing extensions
