### ISSUE TITLE
Bug: `view` displays sessions based on case used during `grade`

### ISSUE THREAD

**Issue by Bubbl3T** [AY2223S1-CS2103T-T12-1/tp#349]
If we have a session `s/Lab1` and we grade a student with `grade 1 s/laB1 g/100`, the result from `view` will display the session name as `s/laB1` instead of `s/Lab1`.

**Comment by RezwanArefin01** [comment]
Perhaps we should capitalize the names in the `parse*` methods? That would prevent bad capitalized name to ever exist in the program! 

Currently the `equal` method of `ModuleClass` and `Session` is also breaking strong equality.

**Comment by RezwanArefin01** [comment]
This is actually fixed in #337. Can you try on `master` branch?
