### ISSUE TITLE
DG Bug: Grade diagram too small

### ISSUE THREAD

**Issue by Berted** [AY2223S1-CS2103T-T12-1/tp#358]
Due to the limitations of Github Pages' margin, the grade diagram shown is too detailed to be visible. Perhaps consider separating it into two separate diagrams?

![image](https://user-images.githubusercontent.com/46164341/200130857-7323bf33-962d-43f1-9004-a9fcaf8d77f3.png)

**Comment by RezwanArefin01** [comment]
Should we remove the call to IndexUtil?

**Comment by Berted** [comment]
> Should we remove the call to IndexUtil?

I believe it would be better if we separate the content within the for loop to another section using reference frames.
