### ISSUE TITLE
Update AboutUs page

### ISSUE THREAD

**Issue by Bubbl3T** [AY2223S1-CS2103T-T12-1/tp#5]
* Add your own details. Include a suitable photo as described in week 7 tP task.
  * If your photo is in jpg format, name the file as .png anyway.
* Indicate the different roles played and responsibilities held by each team member.
* The filename of the profile photo should be docs/images/github_username_in_lower_case.png (Note: lowercase is important)
* There is no need to mention the the tutor/lecturer, but OK to do so too.

Status:
- [x] Edbert
- [x] Jing Xue
- [x] Rezwan
- [x] Xu Yi
- [x] Zechen

**Comment by Berted** [comment]
Resolved by #27 #30 #36 #41 #44.
