### ISSUE TITLE
Consider making each item in student list expandable

### ISSUE THREAD

**Issue by Berted** [AY2223S1-CS2103T-T12-1/tp#77]
Since address, email, and phone number fields are now optional fields. It makes the address book look pretty "empty" if they're non-existent fields. Sample can be seen below:
![image](https://user-images.githubusercontent.com/46164341/193861793-ed4cb5fd-0fb2-4c0e-a361-07e262ba021c.png)

Perhaps we can consider making each item in the list expandable. Below is a rough mock-up by @optionalemon:
![image](https://user-images.githubusercontent.com/46164341/193861286-d3f1bff8-b6b1-41bc-a6d3-f00bfda76f05.png)

This could also be useful come time we want to show scores of a student through the expanded list.

Other ideas are also welcome!

**Comment by Bubbl3T** [comment]
Issue no longer relevant since UI is upgraded.
