### ISSUE TITLE
Remove duplicate calls of requireNonNull checks.

### ISSUE THREAD

**Issue by Bubbl3T** [AY2223S1-CS2103T-T12-1/tp#84]
There are multiple checks of `requireNonNull` for a command call. We can possibly reduce the number of duplicate calls.

_Originally posted by @njxue in https://github.com/AY2223S1-CS2103T-T12-1/tp/pull/80#discussion_r987967438_

**Comment by Berted** [comment]
Hi, I believe @njxue statement doesn't match the title of this issue. I believe this issue in itself should not be a problem for defensive coding reasons? Will be closed for now. Feel free to reopen if you have some thoughts regarding this issue.
