### ISSUE TITLE
Consider changing List to Set.

### ISSUE THREAD

**Issue by Bubbl3T** [AY2223S1-CS2103T-T12-1/tp#85]
Should ordering of module classes matter? Perhaps something to consider. If it doesn't matter, perhaps we can consider using a set instead.

_Originally posted by @Berted in https://github.com/AY2223S1-CS2103T-T12-1/tp/pull/80#discussion_r987928800_

**Comment by Berted** [comment]
Our current implementation is serviceable since we're not optimizing too much for performance anyways. Will be resolved for now as out-of-scope.
