### ISSUE TITLE
As a user, I can group sessions together

### ISSUE THREAD

**Issue by Berted** [AY2223S1-CS2103T-T12-1/tp#91]
...so that I can classify each session, i.e. some are attendance, some are problem sets, etc. 

Justification: This could come in handy when we need to aggregate data, i.e. near the end of the semester, we want to know how many times the student attended tutorial classes, which means we need to give some "idea" for what sessions "are".

**Comment by Bubbl3T** [comment]
Feature discarded as there are no classification on sessions.
